//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g 2012-10-24 22:06:48

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class TTCN3Lexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__26=26;
	public const int BITSTRING=4;
	public const int BOOLEAN=5;
	public const int CHAR=6;
	public const int CHARSTRING=7;
	public const int COMMENT=8;
	public const int ESC_QUOTE=9;
	public const int EXPONENT=10;
	public const int FLOAT=11;
	public const int HEX_DIGIT=12;
	public const int ID=13;
	public const int INT=14;
	public const int INTEGER=15;
	public const int LBRACKET=16;
	public const int OCTAL_ESC=17;
	public const int OCTETSTRING=18;
	public const int OPTIONAL=19;
	public const int RBRACKET=20;
	public const int RECORD=21;
	public const int STRING=22;
	public const int TYPE=23;
	public const int UNICODE_ESC=24;
	public const int WS=25;

    // delegates
    // delegators

	public TTCN3Lexer()
	{
		OnCreated();
	}

	public TTCN3Lexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public TTCN3Lexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__26();
	partial void LeaveRule_T__26();

	// $ANTLR start "T__26"
	[GrammarRule("T__26")]
	private void mT__26()
	{
		EnterRule_T__26();
		EnterRule("T__26", 1);
		TraceIn("T__26", 1);
		try
		{
			int _type = T__26;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:7:7: ( ',' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:7:9: ','
			{
			DebugLocation(7, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__26", 1);
			LeaveRule("T__26", 1);
			LeaveRule_T__26();
		}
	}
	// $ANTLR end "T__26"

	partial void EnterRule_OPTIONAL();
	partial void LeaveRule_OPTIONAL();

	// $ANTLR start "OPTIONAL"
	[GrammarRule("OPTIONAL")]
	private void mOPTIONAL()
	{
		EnterRule_OPTIONAL();
		EnterRule("OPTIONAL", 2);
		TraceIn("OPTIONAL", 2);
		try
		{
			int _type = OPTIONAL;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:66:9: ( 'optional' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:66:11: 'optional'
			{
			DebugLocation(66, 11);
			Match("optional"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OPTIONAL", 2);
			LeaveRule("OPTIONAL", 2);
			LeaveRule_OPTIONAL();
		}
	}
	// $ANTLR end "OPTIONAL"

	partial void EnterRule_BITSTRING();
	partial void LeaveRule_BITSTRING();

	// $ANTLR start "BITSTRING"
	[GrammarRule("BITSTRING")]
	private void mBITSTRING()
	{
		EnterRule_BITSTRING();
		EnterRule("BITSTRING", 3);
		TraceIn("BITSTRING", 3);
		try
		{
			int _type = BITSTRING;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:68:2: ( 'bitstring' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:68:4: 'bitstring'
			{
			DebugLocation(68, 4);
			Match("bitstring"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BITSTRING", 3);
			LeaveRule("BITSTRING", 3);
			LeaveRule_BITSTRING();
		}
	}
	// $ANTLR end "BITSTRING"

	partial void EnterRule_BOOLEAN();
	partial void LeaveRule_BOOLEAN();

	// $ANTLR start "BOOLEAN"
	[GrammarRule("BOOLEAN")]
	private void mBOOLEAN()
	{
		EnterRule_BOOLEAN();
		EnterRule("BOOLEAN", 4);
		TraceIn("BOOLEAN", 4);
		try
		{
			int _type = BOOLEAN;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:69:9: ( 'boolean' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:69:11: 'boolean'
			{
			DebugLocation(69, 11);
			Match("boolean"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BOOLEAN", 4);
			LeaveRule("BOOLEAN", 4);
			LeaveRule_BOOLEAN();
		}
	}
	// $ANTLR end "BOOLEAN"

	partial void EnterRule_CHARSTRING();
	partial void LeaveRule_CHARSTRING();

	// $ANTLR start "CHARSTRING"
	[GrammarRule("CHARSTRING")]
	private void mCHARSTRING()
	{
		EnterRule_CHARSTRING();
		EnterRule("CHARSTRING", 5);
		TraceIn("CHARSTRING", 5);
		try
		{
			int _type = CHARSTRING;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:71:2: ( 'charstring' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:71:4: 'charstring'
			{
			DebugLocation(71, 4);
			Match("charstring"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CHARSTRING", 5);
			LeaveRule("CHARSTRING", 5);
			LeaveRule_CHARSTRING();
		}
	}
	// $ANTLR end "CHARSTRING"

	partial void EnterRule_CHAR();
	partial void LeaveRule_CHAR();

	// $ANTLR start "CHAR"
	[GrammarRule("CHAR")]
	private void mCHAR()
	{
		EnterRule_CHAR();
		EnterRule("CHAR", 6);
		TraceIn("CHAR", 6);
		try
		{
			int _type = CHAR;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:72:6: ( 'char' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:72:8: 'char'
			{
			DebugLocation(72, 8);
			Match("char"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CHAR", 6);
			LeaveRule("CHAR", 6);
			LeaveRule_CHAR();
		}
	}
	// $ANTLR end "CHAR"

	partial void EnterRule_INTEGER();
	partial void LeaveRule_INTEGER();

	// $ANTLR start "INTEGER"
	[GrammarRule("INTEGER")]
	private void mINTEGER()
	{
		EnterRule_INTEGER();
		EnterRule("INTEGER", 7);
		TraceIn("INTEGER", 7);
		try
		{
			int _type = INTEGER;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:73:9: ( 'integer' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:73:11: 'integer'
			{
			DebugLocation(73, 11);
			Match("integer"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INTEGER", 7);
			LeaveRule("INTEGER", 7);
			LeaveRule_INTEGER();
		}
	}
	// $ANTLR end "INTEGER"

	partial void EnterRule_OCTETSTRING();
	partial void LeaveRule_OCTETSTRING();

	// $ANTLR start "OCTETSTRING"
	[GrammarRule("OCTETSTRING")]
	private void mOCTETSTRING()
	{
		EnterRule_OCTETSTRING();
		EnterRule("OCTETSTRING", 8);
		TraceIn("OCTETSTRING", 8);
		try
		{
			int _type = OCTETSTRING;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:75:2: ( 'octetstring' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:75:4: 'octetstring'
			{
			DebugLocation(75, 4);
			Match("octetstring"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OCTETSTRING", 8);
			LeaveRule("OCTETSTRING", 8);
			LeaveRule_OCTETSTRING();
		}
	}
	// $ANTLR end "OCTETSTRING"

	partial void EnterRule_RECORD();
	partial void LeaveRule_RECORD();

	// $ANTLR start "RECORD"
	[GrammarRule("RECORD")]
	private void mRECORD()
	{
		EnterRule_RECORD();
		EnterRule("RECORD", 9);
		TraceIn("RECORD", 9);
		try
		{
			int _type = RECORD;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:76:8: ( 'record' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:76:10: 'record'
			{
			DebugLocation(76, 10);
			Match("record"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RECORD", 9);
			LeaveRule("RECORD", 9);
			LeaveRule_RECORD();
		}
	}
	// $ANTLR end "RECORD"

	partial void EnterRule_TYPE();
	partial void LeaveRule_TYPE();

	// $ANTLR start "TYPE"
	[GrammarRule("TYPE")]
	private void mTYPE()
	{
		EnterRule_TYPE();
		EnterRule("TYPE", 10);
		TraceIn("TYPE", 10);
		try
		{
			int _type = TYPE;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:77:7: ( 'type' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:77:9: 'type'
			{
			DebugLocation(77, 9);
			Match("type"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TYPE", 10);
			LeaveRule("TYPE", 10);
			LeaveRule_TYPE();
		}
	}
	// $ANTLR end "TYPE"

	partial void EnterRule_LBRACKET();
	partial void LeaveRule_LBRACKET();

	// $ANTLR start "LBRACKET"
	[GrammarRule("LBRACKET")]
	private void mLBRACKET()
	{
		EnterRule_LBRACKET();
		EnterRule("LBRACKET", 11);
		TraceIn("LBRACKET", 11);
		try
		{
			int _type = LBRACKET;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:78:9: ( '{' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:78:11: '{'
			{
			DebugLocation(78, 11);
			Match('{'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LBRACKET", 11);
			LeaveRule("LBRACKET", 11);
			LeaveRule_LBRACKET();
		}
	}
	// $ANTLR end "LBRACKET"

	partial void EnterRule_RBRACKET();
	partial void LeaveRule_RBRACKET();

	// $ANTLR start "RBRACKET"
	[GrammarRule("RBRACKET")]
	private void mRBRACKET()
	{
		EnterRule_RBRACKET();
		EnterRule("RBRACKET", 12);
		TraceIn("RBRACKET", 12);
		try
		{
			int _type = RBRACKET;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:79:9: ( '}' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:79:11: '}'
			{
			DebugLocation(79, 11);
			Match('}'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RBRACKET", 12);
			LeaveRule("RBRACKET", 12);
			LeaveRule_RBRACKET();
		}
	}
	// $ANTLR end "RBRACKET"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 13);
		TraceIn("ID", 13);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:81:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:81:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(81, 7);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(81, 31);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:81:31: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if (((LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(81, 31);
					input.Consume();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 13);
			LeaveRule("ID", 13);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 14);
		TraceIn("INT", 14);
		try
		{
			int _type = INT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:84:5: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:84:7: ( '0' .. '9' )+
			{
			DebugLocation(84, 7);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:84:7: ( '0' .. '9' )+
			int cnt2=0;
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if (((LA2_0>='0' && LA2_0<='9')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(84, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt2 >= 1)
						goto loop2;

					EarlyExitException eee2 = new EarlyExitException( 2, input );
					DebugRecognitionException(eee2);
					throw eee2;
				}
				cnt2++;
			}
			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INT", 14);
			LeaveRule("INT", 14);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 15);
		TraceIn("FLOAT", 15);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
			int alt9=3;
			try { DebugEnterDecision(9, false);
			try
			{
				alt9 = dfa9.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
				{
				DebugLocation(88, 9);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:9: ( '0' .. '9' )+
				int cnt3=0;
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_0 = input.LA(1);

					if (((LA3_0>='0' && LA3_0<='9')))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch (alt3)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(88, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt3 >= 1)
							goto loop3;

						EarlyExitException eee3 = new EarlyExitException( 3, input );
						DebugRecognitionException(eee3);
						throw eee3;
					}
					cnt3++;
				}
				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(88, 21);
				Match('.'); 
				DebugLocation(88, 25);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:25: ( '0' .. '9' )*
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_0 = input.LA(1);

					if (((LA4_0>='0' && LA4_0<='9')))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch ( alt4 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(88, 25);
						input.Consume();


						}
						break;

					default:
						goto loop4;
					}
				}

				loop4:
					;

				} finally { DebugExitSubRule(4); }

				DebugLocation(88, 37);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:37: ( EXPONENT )?
				int alt5=2;
				try { DebugEnterSubRule(5);
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if ((LA5_0=='E'||LA5_0=='e'))
				{
					alt5 = 1;
				}
				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:88:37: EXPONENT
					{
					DebugLocation(88, 37);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(5); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:89:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
				{
				DebugLocation(89, 9);
				Match('.'); 
				DebugLocation(89, 13);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:89:13: ( '0' .. '9' )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if (((LA6_0>='0' && LA6_0<='9')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(89, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(89, 25);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:89:25: ( EXPONENT )?
				int alt7=2;
				try { DebugEnterSubRule(7);
				try { DebugEnterDecision(7, false);
				int LA7_0 = input.LA(1);

				if ((LA7_0=='E'||LA7_0=='e'))
				{
					alt7 = 1;
				}
				} finally { DebugExitDecision(7); }
				switch (alt7)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:89:25: EXPONENT
					{
					DebugLocation(89, 25);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(7); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:90:9: ( '0' .. '9' )+ EXPONENT
				{
				DebugLocation(90, 9);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:90:9: ( '0' .. '9' )+
				int cnt8=0;
				try { DebugEnterSubRule(8);
				while (true)
				{
					int alt8=2;
					try { DebugEnterDecision(8, false);
					int LA8_0 = input.LA(1);

					if (((LA8_0>='0' && LA8_0<='9')))
					{
						alt8 = 1;
					}


					} finally { DebugExitDecision(8); }
					switch (alt8)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(90, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt8 >= 1)
							goto loop8;

						EarlyExitException eee8 = new EarlyExitException( 8, input );
						DebugRecognitionException(eee8);
						throw eee8;
					}
					cnt8++;
				}
				loop8:
					;

				} finally { DebugExitSubRule(8); }

				DebugLocation(90, 21);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 15);
			LeaveRule("FLOAT", 15);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 16);
		TraceIn("COMMENT", 16);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:94:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )
			int alt13=2;
			try { DebugEnterDecision(13, false);
			int LA13_0 = input.LA(1);

			if ((LA13_0=='/'))
			{
				int LA13_1 = input.LA(2);

				if ((LA13_1=='/'))
				{
					alt13 = 1;
				}
				else if ((LA13_1=='*'))
				{
					alt13 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:94:9: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
				{
				DebugLocation(94, 9);
				Match("//"); 

				DebugLocation(94, 14);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:94:14: (~ ( '\\n' | '\\r' ) )*
				try { DebugEnterSubRule(10);
				while (true)
				{
					int alt10=2;
					try { DebugEnterDecision(10, false);
					int LA10_0 = input.LA(1);

					if (((LA10_0>='\u0000' && LA10_0<='\t')||(LA10_0>='\u000B' && LA10_0<='\f')||(LA10_0>='\u000E' && LA10_0<='\uFFFF')))
					{
						alt10 = 1;
					}


					} finally { DebugExitDecision(10); }
					switch ( alt10 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(94, 14);
						input.Consume();


						}
						break;

					default:
						goto loop10;
					}
				}

				loop10:
					;

				} finally { DebugExitSubRule(10); }

				DebugLocation(94, 28);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:94:28: ( '\\r' )?
				int alt11=2;
				try { DebugEnterSubRule(11);
				try { DebugEnterDecision(11, false);
				int LA11_0 = input.LA(1);

				if ((LA11_0=='\r'))
				{
					alt11 = 1;
				}
				} finally { DebugExitDecision(11); }
				switch (alt11)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:94:28: '\\r'
					{
					DebugLocation(94, 28);
					Match('\r'); 

					}
					break;

				}
				} finally { DebugExitSubRule(11); }

				DebugLocation(94, 34);
				Match('\n'); 
				DebugLocation(94, 39);
				_channel=Hidden;

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:95:9: '/*' ( options {greedy=false; } : . )* '*/'
				{
				DebugLocation(95, 9);
				Match("/*"); 

				DebugLocation(95, 14);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:95:14: ( options {greedy=false; } : . )*
				try { DebugEnterSubRule(12);
				while (true)
				{
					int alt12=2;
					try { DebugEnterDecision(12, false);
					int LA12_0 = input.LA(1);

					if ((LA12_0=='*'))
					{
						int LA12_1 = input.LA(2);

						if ((LA12_1=='/'))
						{
							alt12 = 2;
						}
						else if (((LA12_1>='\u0000' && LA12_1<='.')||(LA12_1>='0' && LA12_1<='\uFFFF')))
						{
							alt12 = 1;
						}


					}
					else if (((LA12_0>='\u0000' && LA12_0<=')')||(LA12_0>='+' && LA12_0<='\uFFFF')))
					{
						alt12 = 1;
					}


					} finally { DebugExitDecision(12); }
					switch ( alt12 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:95:42: .
						{
						DebugLocation(95, 42);
						MatchAny(); 

						}
						break;

					default:
						goto loop12;
					}
				}

				loop12:
					;

				} finally { DebugExitSubRule(12); }

				DebugLocation(95, 47);
				Match("*/"); 

				DebugLocation(95, 52);
				_channel=Hidden;

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 16);
			LeaveRule("COMMENT", 16);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 17);
		TraceIn("WS", 17);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:98:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:98:9: ( ' ' | '\\t' | '\\r' | '\\n' )
			{
			DebugLocation(98, 9);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(102, 11);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 17);
			LeaveRule("WS", 17);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 18);
		TraceIn("STRING", 18);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:106:5: ( '\"' ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:106:8: '\"' ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(106, 8);
			Match('\"'); 
			DebugLocation(106, 12);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:106:12: ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=3;
				try { DebugEnterDecision(14, false);
				int LA14_0 = input.LA(1);

				if ((LA14_0=='\"'))
				{
					int LA14_1 = input.LA(2);

					if ((LA14_1=='\"'))
					{
						alt14 = 1;
					}


				}
				else if (((LA14_0>='\u0000' && LA14_0<='!')||(LA14_0>='#' && LA14_0<='[')||(LA14_0>=']' && LA14_0<='\uFFFF')))
				{
					alt14 = 2;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:106:14: ESC_QUOTE
					{
					DebugLocation(106, 14);
					mESC_QUOTE(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:106:26: ~ ( '\\\\' | '\"' )
					{
					DebugLocation(106, 26);
					input.Consume();


					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(106, 41);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 18);
			LeaveRule("STRING", 18);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 19);
		TraceIn("EXPONENT", 19);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:111:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:111:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(111, 12);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(111, 22);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:111:22: ( '+' | '-' )?
			int alt15=2;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_0 = input.LA(1);

			if ((LA15_0=='+'||LA15_0=='-'))
			{
				alt15 = 1;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
				{
				DebugLocation(111, 22);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(15); }

			DebugLocation(111, 33);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:111:33: ( '0' .. '9' )+
			int cnt16=0;
			try { DebugEnterSubRule(16);
			while (true)
			{
				int alt16=2;
				try { DebugEnterDecision(16, false);
				int LA16_0 = input.LA(1);

				if (((LA16_0>='0' && LA16_0<='9')))
				{
					alt16 = 1;
				}


				} finally { DebugExitDecision(16); }
				switch (alt16)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(111, 33);
					input.Consume();


					}
					break;

				default:
					if (cnt16 >= 1)
						goto loop16;

					EarlyExitException eee16 = new EarlyExitException( 16, input );
					DebugRecognitionException(eee16);
					throw eee16;
				}
				cnt16++;
			}
			loop16:
				;

			} finally { DebugExitSubRule(16); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 19);
			LeaveRule("EXPONENT", 19);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 20);
		TraceIn("HEX_DIGIT", 20);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:114:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
			{
			DebugLocation(114, 11);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 20);
			LeaveRule("HEX_DIGIT", 20);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_ESC_QUOTE();
	partial void LeaveRule_ESC_QUOTE();

	// $ANTLR start "ESC_QUOTE"
	[GrammarRule("ESC_QUOTE")]
	private void mESC_QUOTE()
	{
		EnterRule_ESC_QUOTE();
		EnterRule("ESC_QUOTE", 21);
		TraceIn("ESC_QUOTE", 21);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:118:5: ( '\"' '\"' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:118:9: '\"' '\"'
			{
			DebugLocation(118, 9);
			Match('\"'); 
			DebugLocation(118, 13);
			Match('\"'); 

			}

		}
		finally
		{
			TraceOut("ESC_QUOTE", 21);
			LeaveRule("ESC_QUOTE", 21);
			LeaveRule_ESC_QUOTE();
		}
	}
	// $ANTLR end "ESC_QUOTE"

	partial void EnterRule_OCTAL_ESC();
	partial void LeaveRule_OCTAL_ESC();

	// $ANTLR start "OCTAL_ESC"
	[GrammarRule("OCTAL_ESC")]
	private void mOCTAL_ESC()
	{
		EnterRule_OCTAL_ESC();
		EnterRule("OCTAL_ESC", 22);
		TraceIn("OCTAL_ESC", 22);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:123:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt17=3;
			try { DebugEnterDecision(17, false);
			int LA17_0 = input.LA(1);

			if ((LA17_0=='\\'))
			{
				int LA17_1 = input.LA(2);

				if (((LA17_1>='0' && LA17_1<='3')))
				{
					int LA17_2 = input.LA(3);

					if (((LA17_2>='0' && LA17_2<='7')))
					{
						int LA17_4 = input.LA(4);

						if (((LA17_4>='0' && LA17_4<='7')))
						{
							alt17 = 1;
						}
						else
						{
							alt17 = 2;
						}
					}
					else
					{
						alt17 = 3;
					}
				}
				else if (((LA17_1>='4' && LA17_1<='7')))
				{
					int LA17_3 = input.LA(3);

					if (((LA17_3>='0' && LA17_3<='7')))
					{
						alt17 = 2;
					}
					else
					{
						alt17 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 17, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 17, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(17); }
			switch (alt17)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:123:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(123, 9);
				Match('\\'); 
				DebugLocation(123, 14);
				input.Consume();

				DebugLocation(123, 25);
				input.Consume();

				DebugLocation(123, 36);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:124:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(124, 9);
				Match('\\'); 
				DebugLocation(124, 14);
				input.Consume();

				DebugLocation(124, 25);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:125:9: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(125, 9);
				Match('\\'); 
				DebugLocation(125, 14);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCTAL_ESC", 22);
			LeaveRule("OCTAL_ESC", 22);
			LeaveRule_OCTAL_ESC();
		}
	}
	// $ANTLR end "OCTAL_ESC"

	partial void EnterRule_UNICODE_ESC();
	partial void LeaveRule_UNICODE_ESC();

	// $ANTLR start "UNICODE_ESC"
	[GrammarRule("UNICODE_ESC")]
	private void mUNICODE_ESC()
	{
		EnterRule_UNICODE_ESC();
		EnterRule("UNICODE_ESC", 23);
		TraceIn("UNICODE_ESC", 23);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:130:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:130:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
			{
			DebugLocation(130, 9);
			Match('\\'); 
			DebugLocation(130, 14);
			Match('u'); 
			DebugLocation(130, 18);
			mHEX_DIGIT(); 
			DebugLocation(130, 28);
			mHEX_DIGIT(); 
			DebugLocation(130, 38);
			mHEX_DIGIT(); 
			DebugLocation(130, 48);
			mHEX_DIGIT(); 

			}

		}
		finally
		{
			TraceOut("UNICODE_ESC", 23);
			LeaveRule("UNICODE_ESC", 23);
			LeaveRule_UNICODE_ESC();
		}
	}
	// $ANTLR end "UNICODE_ESC"

	public override void mTokens()
	{
		// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:8: ( T__26 | OPTIONAL | BITSTRING | BOOLEAN | CHARSTRING | CHAR | INTEGER | OCTETSTRING | RECORD | TYPE | LBRACKET | RBRACKET | ID | INT | FLOAT | COMMENT | WS | STRING )
		int alt18=18;
		try { DebugEnterDecision(18, false);
		try
		{
			alt18 = dfa18.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(18); }
		switch (alt18)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:10: T__26
			{
			DebugLocation(1, 10);
			mT__26(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:16: OPTIONAL
			{
			DebugLocation(1, 16);
			mOPTIONAL(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:25: BITSTRING
			{
			DebugLocation(1, 25);
			mBITSTRING(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:35: BOOLEAN
			{
			DebugLocation(1, 35);
			mBOOLEAN(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:43: CHARSTRING
			{
			DebugLocation(1, 43);
			mCHARSTRING(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:54: CHAR
			{
			DebugLocation(1, 54);
			mCHAR(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:59: INTEGER
			{
			DebugLocation(1, 59);
			mINTEGER(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:67: OCTETSTRING
			{
			DebugLocation(1, 67);
			mOCTETSTRING(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:79: RECORD
			{
			DebugLocation(1, 79);
			mRECORD(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:86: TYPE
			{
			DebugLocation(1, 86);
			mTYPE(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:91: LBRACKET
			{
			DebugLocation(1, 91);
			mLBRACKET(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:100: RBRACKET
			{
			DebugLocation(1, 100);
			mRBRACKET(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:109: ID
			{
			DebugLocation(1, 109);
			mID(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:112: INT
			{
			DebugLocation(1, 112);
			mINT(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:116: FLOAT
			{
			DebugLocation(1, 116);
			mFLOAT(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:122: COMMENT
			{
			DebugLocation(1, 122);
			mCOMMENT(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:130: WS
			{
			DebugLocation(1, 130);
			mWS(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:133: STRING
			{
			DebugLocation(1, 133);
			mSTRING(); 

			}
			break;

		}

	}


	#region DFA
	DFA9 dfa9;
	DFA18 dfa18;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa9 = new DFA9(this);
		dfa18 = new DFA18(this);
	}

	private class DFA9 : DFA
	{
		private const string DFA9_eotS =
			"\x5\xFFFF";
		private const string DFA9_eofS =
			"\x5\xFFFF";
		private const string DFA9_minS =
			"\x2\x2E\x3\xFFFF";
		private const string DFA9_maxS =
			"\x1\x39\x1\x65\x3\xFFFF";
		private const string DFA9_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1\x1\x3";
		private const string DFA9_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA9_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"",
				""
			};

		private static readonly short[] DFA9_eot = DFA.UnpackEncodedString(DFA9_eotS);
		private static readonly short[] DFA9_eof = DFA.UnpackEncodedString(DFA9_eofS);
		private static readonly char[] DFA9_min = DFA.UnpackEncodedStringToUnsignedChars(DFA9_minS);
		private static readonly char[] DFA9_max = DFA.UnpackEncodedStringToUnsignedChars(DFA9_maxS);
		private static readonly short[] DFA9_accept = DFA.UnpackEncodedString(DFA9_acceptS);
		private static readonly short[] DFA9_special = DFA.UnpackEncodedString(DFA9_specialS);
		private static readonly short[][] DFA9_transition;

		static DFA9()
		{
			int numStates = DFA9_transitionS.Length;
			DFA9_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA9_transition[i] = DFA.UnpackEncodedString(DFA9_transitionS[i]);
			}
		}

		public DFA9( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 9;
			this.eot = DFA9_eot;
			this.eof = DFA9_eof;
			this.min = DFA9_min;
			this.max = DFA9_max;
			this.accept = DFA9_accept;
			this.special = DFA9_special;
			this.transition = DFA9_transition;
		}

		public override string Description { get { return "87:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA18 : DFA
	{
		private const string DFA18_eotS =
			"\x2\xFFFF\x6\xA\x3\xFFFF\x1\x18\x4\xFFFF\x8\xA\x1\xFFFF\xC\xA\x1\x2E"+
			"\x2\xA\x1\x31\x5\xA\x1\xFFFF\x2\xA\x1\xFFFF\x6\xA\x1\x3F\x3\xA\x1\x43"+
			"\x1\xA\x1\x45\x1\xFFFF\x1\x46\x2\xA\x1\xFFFF\x1\xA\x2\xFFFF\x1\xA\x1"+
			"\x4B\x2\xA\x1\xFFFF\x1\x4E\x1\x4F\x2\xFFFF";
		private const string DFA18_eofS =
			"\x50\xFFFF";
		private const string DFA18_minS =
			"\x1\x9\x1\xFFFF\x1\x63\x1\x69\x1\x68\x1\x6E\x1\x65\x1\x79\x3\xFFFF\x1"+
			"\x2E\x4\xFFFF\x3\x74\x1\x6F\x1\x61\x1\x74\x1\x63\x1\x70\x1\xFFFF\x1\x69"+
			"\x1\x65\x1\x73\x1\x6C\x1\x72\x1\x65\x1\x6F\x1\x65\x1\x6F\x2\x74\x1\x65"+
			"\x1\x30\x1\x67\x1\x72\x1\x30\x1\x6E\x1\x73\x1\x72\x1\x61\x1\x74\x1\xFFFF"+
			"\x1\x65\x1\x64\x1\xFFFF\x1\x61\x1\x74\x1\x69\x1\x6E\x2\x72\x1\x30\x1"+
			"\x6C\x1\x72\x1\x6E\x1\x30\x1\x69\x1\x30\x1\xFFFF\x1\x30\x1\x69\x1\x67"+
			"\x1\xFFFF\x1\x6E\x2\xFFFF\x1\x6E\x1\x30\x2\x67\x1\xFFFF\x2\x30\x2\xFFFF";
		private const string DFA18_maxS =
			"\x1\x7D\x1\xFFFF\x1\x70\x1\x6F\x1\x68\x1\x6E\x1\x65\x1\x79\x3\xFFFF\x1"+
			"\x65\x4\xFFFF\x3\x74\x1\x6F\x1\x61\x1\x74\x1\x63\x1\x70\x1\xFFFF\x1\x69"+
			"\x1\x65\x1\x73\x1\x6C\x1\x72\x1\x65\x1\x6F\x1\x65\x1\x6F\x2\x74\x1\x65"+
			"\x1\x7A\x1\x67\x1\x72\x1\x7A\x1\x6E\x1\x73\x1\x72\x1\x61\x1\x74\x1\xFFFF"+
			"\x1\x65\x1\x64\x1\xFFFF\x1\x61\x1\x74\x1\x69\x1\x6E\x2\x72\x1\x7A\x1"+
			"\x6C\x1\x72\x1\x6E\x1\x7A\x1\x69\x1\x7A\x1\xFFFF\x1\x7A\x1\x69\x1\x67"+
			"\x1\xFFFF\x1\x6E\x2\xFFFF\x1\x6E\x1\x7A\x2\x67\x1\xFFFF\x2\x7A\x2\xFFFF";
		private const string DFA18_acceptS =
			"\x1\xFFFF\x1\x1\x6\xFFFF\x1\xB\x1\xC\x1\xD\x1\xFFFF\x1\xF\x1\x10\x1\x11"+
			"\x1\x12\x8\xFFFF\x1\xE\x15\xFFFF\x1\x6\x2\xFFFF\x1\xA\xD\xFFFF\x1\x9"+
			"\x3\xFFFF\x1\x4\x1\xFFFF\x1\x7\x1\x2\x4\xFFFF\x1\x3\x2\xFFFF\x1\x5\x1"+
			"\x8";
		private const string DFA18_specialS =
			"\x50\xFFFF}>";
		private static readonly string[] DFA18_transitionS =
			{
				"\x2\xE\x2\xFFFF\x1\xE\x12\xFFFF\x1\xE\x1\xFFFF\x1\xF\x9\xFFFF\x1\x1"+
				"\x1\xFFFF\x1\xC\x1\xD\xA\xB\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF"+
				"\x1\xA\x1\x3\x1\x4\x5\xA\x1\x5\x5\xA\x1\x2\x2\xA\x1\x6\x1\xA\x1\x7\x6"+
				"\xA\x1\x8\x1\xFFFF\x1\x9",
				"",
				"\x1\x11\xC\xFFFF\x1\x10",
				"\x1\x12\x5\xFFFF\x1\x13",
				"\x1\x14",
				"\x1\x15",
				"\x1\x16",
				"\x1\x17",
				"",
				"",
				"",
				"\x1\xC\x1\xFFFF\xA\xB\xB\xFFFF\x1\xC\x1F\xFFFF\x1\xC",
				"",
				"",
				"",
				"",
				"\x1\x19",
				"\x1\x1A",
				"\x1\x1B",
				"\x1\x1C",
				"\x1\x1D",
				"\x1\x1E",
				"\x1\x1F",
				"\x1\x20",
				"",
				"\x1\x21",
				"\x1\x22",
				"\x1\x23",
				"\x1\x24",
				"\x1\x25",
				"\x1\x26",
				"\x1\x27",
				"\x1\x28",
				"\x1\x29",
				"\x1\x2A",
				"\x1\x2B",
				"\x1\x2C",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x12\xA\x1\x2D\x7\xA",
				"\x1\x2F",
				"\x1\x30",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\x1\x32",
				"\x1\x33",
				"\x1\x34",
				"\x1\x35",
				"\x1\x36",
				"",
				"\x1\x37",
				"\x1\x38",
				"",
				"\x1\x39",
				"\x1\x3A",
				"\x1\x3B",
				"\x1\x3C",
				"\x1\x3D",
				"\x1\x3E",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\x1\x40",
				"\x1\x41",
				"\x1\x42",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\x1\x44",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\x1\x47",
				"\x1\x48",
				"",
				"\x1\x49",
				"",
				"",
				"\x1\x4A",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\x1\x4C",
				"\x1\x4D",
				"",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"\xA\xA\x7\xFFFF\x1A\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1A\xA",
				"",
				""
			};

		private static readonly short[] DFA18_eot = DFA.UnpackEncodedString(DFA18_eotS);
		private static readonly short[] DFA18_eof = DFA.UnpackEncodedString(DFA18_eofS);
		private static readonly char[] DFA18_min = DFA.UnpackEncodedStringToUnsignedChars(DFA18_minS);
		private static readonly char[] DFA18_max = DFA.UnpackEncodedStringToUnsignedChars(DFA18_maxS);
		private static readonly short[] DFA18_accept = DFA.UnpackEncodedString(DFA18_acceptS);
		private static readonly short[] DFA18_special = DFA.UnpackEncodedString(DFA18_specialS);
		private static readonly short[][] DFA18_transition;

		static DFA18()
		{
			int numStates = DFA18_transitionS.Length;
			DFA18_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA18_transition[i] = DFA.UnpackEncodedString(DFA18_transitionS[i]);
			}
		}

		public DFA18( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 18;
			this.eot = DFA18_eot;
			this.eof = DFA18_eof;
			this.min = DFA18_min;
			this.max = DFA18_max;
			this.accept = DFA18_accept;
			this.special = DFA18_special;
			this.transition = DFA18_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__26 | OPTIONAL | BITSTRING | BOOLEAN | CHARSTRING | CHAR | INTEGER | OCTETSTRING | RECORD | TYPE | LBRACKET | RBRACKET | ID | INT | FLOAT | COMMENT | WS | STRING );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
