//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g 2012-10-24 20:28:47

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class TTCN3 : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int COMMENT=4;
	public const int ESC_QUOTE=5;
	public const int EXPONENT=6;
	public const int FLOAT=7;
	public const int HEX_DIGIT=8;
	public const int ID=9;
	public const int INT=10;
	public const int OCTAL_ESC=11;
	public const int STRING=12;
	public const int TYPE=13;
	public const int UNICODE_ESC=14;
	public const int WS=15;

	    public static void Main(string[] args) {
	        var fileStream = new ANTLRFileStream(args[0]);
	        var lex = new TTCN3(fileStream);
	 
	        try {
	            while (fileStream.LA(1) != CharStreamConstants.EndOfFile)
	            {
	              var token = lex.NextToken();
	              if (token.Channel != TokenChannels.Hidden)
	              {
	                Console.WriteLine("Found token {0}", token);
	              }
	            }
	        } catch (Exception e)  {
	            Console.Error.WriteLine(e.StackTrace);
	        }
	    }


    // delegates
    // delegators

	public TTCN3()
	{
		OnCreated();
	}

	public TTCN3(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public TTCN3(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_TYPE();
	partial void LeaveRule_TYPE();

	// $ANTLR start "TYPE"
	[GrammarRule("TYPE")]
	private void mTYPE()
	{
		EnterRule_TYPE();
		EnterRule("TYPE", 1);
		TraceIn("TYPE", 1);
		try
		{
			int _type = TYPE;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:32:7: ( 'type' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:32:9: 'type'
			{
			DebugLocation(32, 9);
			Match("type"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("TYPE", 1);
			LeaveRule("TYPE", 1);
			LeaveRule_TYPE();
		}
	}
	// $ANTLR end "TYPE"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 2);
		TraceIn("ID", 2);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:35:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:35:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(35, 7);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(35, 31);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:35:31: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if (((LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z')))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(35, 31);
					input.Consume();


					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 2);
			LeaveRule("ID", 2);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 3);
		TraceIn("INT", 3);
		try
		{
			int _type = INT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:38:5: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:38:7: ( '0' .. '9' )+
			{
			DebugLocation(38, 7);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:38:7: ( '0' .. '9' )+
			int cnt2=0;
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=2;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if (((LA2_0>='0' && LA2_0<='9')))
				{
					alt2 = 1;
				}


				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(38, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt2 >= 1)
						goto loop2;

					EarlyExitException eee2 = new EarlyExitException( 2, input );
					DebugRecognitionException(eee2);
					throw eee2;
				}
				cnt2++;
			}
			loop2:
				;

			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INT", 3);
			LeaveRule("INT", 3);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_FLOAT();
	partial void LeaveRule_FLOAT();

	// $ANTLR start "FLOAT"
	[GrammarRule("FLOAT")]
	private void mFLOAT()
	{
		EnterRule_FLOAT();
		EnterRule("FLOAT", 4);
		TraceIn("FLOAT", 4);
		try
		{
			int _type = FLOAT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:5: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT )
			int alt9=3;
			try { DebugEnterDecision(9, false);
			try
			{
				alt9 = dfa9.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:9: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
				{
				DebugLocation(42, 9);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:9: ( '0' .. '9' )+
				int cnt3=0;
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_0 = input.LA(1);

					if (((LA3_0>='0' && LA3_0<='9')))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch (alt3)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(42, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt3 >= 1)
							goto loop3;

						EarlyExitException eee3 = new EarlyExitException( 3, input );
						DebugRecognitionException(eee3);
						throw eee3;
					}
					cnt3++;
				}
				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(42, 21);
				Match('.'); 
				DebugLocation(42, 25);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:25: ( '0' .. '9' )*
				try { DebugEnterSubRule(4);
				while (true)
				{
					int alt4=2;
					try { DebugEnterDecision(4, false);
					int LA4_0 = input.LA(1);

					if (((LA4_0>='0' && LA4_0<='9')))
					{
						alt4 = 1;
					}


					} finally { DebugExitDecision(4); }
					switch ( alt4 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(42, 25);
						input.Consume();


						}
						break;

					default:
						goto loop4;
					}
				}

				loop4:
					;

				} finally { DebugExitSubRule(4); }

				DebugLocation(42, 37);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:37: ( EXPONENT )?
				int alt5=2;
				try { DebugEnterSubRule(5);
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if ((LA5_0=='E'||LA5_0=='e'))
				{
					alt5 = 1;
				}
				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:42:37: EXPONENT
					{
					DebugLocation(42, 37);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(5); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:43:9: '.' ( '0' .. '9' )+ ( EXPONENT )?
				{
				DebugLocation(43, 9);
				Match('.'); 
				DebugLocation(43, 13);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:43:13: ( '0' .. '9' )+
				int cnt6=0;
				try { DebugEnterSubRule(6);
				while (true)
				{
					int alt6=2;
					try { DebugEnterDecision(6, false);
					int LA6_0 = input.LA(1);

					if (((LA6_0>='0' && LA6_0<='9')))
					{
						alt6 = 1;
					}


					} finally { DebugExitDecision(6); }
					switch (alt6)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(43, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt6 >= 1)
							goto loop6;

						EarlyExitException eee6 = new EarlyExitException( 6, input );
						DebugRecognitionException(eee6);
						throw eee6;
					}
					cnt6++;
				}
				loop6:
					;

				} finally { DebugExitSubRule(6); }

				DebugLocation(43, 25);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:43:25: ( EXPONENT )?
				int alt7=2;
				try { DebugEnterSubRule(7);
				try { DebugEnterDecision(7, false);
				int LA7_0 = input.LA(1);

				if ((LA7_0=='E'||LA7_0=='e'))
				{
					alt7 = 1;
				}
				} finally { DebugExitDecision(7); }
				switch (alt7)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:43:25: EXPONENT
					{
					DebugLocation(43, 25);
					mEXPONENT(); 

					}
					break;

				}
				} finally { DebugExitSubRule(7); }


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:44:9: ( '0' .. '9' )+ EXPONENT
				{
				DebugLocation(44, 9);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:44:9: ( '0' .. '9' )+
				int cnt8=0;
				try { DebugEnterSubRule(8);
				while (true)
				{
					int alt8=2;
					try { DebugEnterDecision(8, false);
					int LA8_0 = input.LA(1);

					if (((LA8_0>='0' && LA8_0<='9')))
					{
						alt8 = 1;
					}


					} finally { DebugExitDecision(8); }
					switch (alt8)
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(44, 9);
						input.Consume();


						}
						break;

					default:
						if (cnt8 >= 1)
							goto loop8;

						EarlyExitException eee8 = new EarlyExitException( 8, input );
						DebugRecognitionException(eee8);
						throw eee8;
					}
					cnt8++;
				}
				loop8:
					;

				} finally { DebugExitSubRule(8); }

				DebugLocation(44, 21);
				mEXPONENT(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FLOAT", 4);
			LeaveRule("FLOAT", 4);
			LeaveRule_FLOAT();
		}
	}
	// $ANTLR end "FLOAT"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 5);
		TraceIn("COMMENT", 5);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:48:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )
			int alt13=2;
			try { DebugEnterDecision(13, false);
			int LA13_0 = input.LA(1);

			if ((LA13_0=='/'))
			{
				int LA13_1 = input.LA(2);

				if ((LA13_1=='/'))
				{
					alt13 = 1;
				}
				else if ((LA13_1=='*'))
				{
					alt13 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 13, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:48:9: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
				{
				DebugLocation(48, 9);
				Match("//"); 

				DebugLocation(48, 14);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:48:14: (~ ( '\\n' | '\\r' ) )*
				try { DebugEnterSubRule(10);
				while (true)
				{
					int alt10=2;
					try { DebugEnterDecision(10, false);
					int LA10_0 = input.LA(1);

					if (((LA10_0>='\u0000' && LA10_0<='\t')||(LA10_0>='\u000B' && LA10_0<='\f')||(LA10_0>='\u000E' && LA10_0<='\uFFFF')))
					{
						alt10 = 1;
					}


					} finally { DebugExitDecision(10); }
					switch ( alt10 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
						{
						DebugLocation(48, 14);
						input.Consume();


						}
						break;

					default:
						goto loop10;
					}
				}

				loop10:
					;

				} finally { DebugExitSubRule(10); }

				DebugLocation(48, 28);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:48:28: ( '\\r' )?
				int alt11=2;
				try { DebugEnterSubRule(11);
				try { DebugEnterDecision(11, false);
				int LA11_0 = input.LA(1);

				if ((LA11_0=='\r'))
				{
					alt11 = 1;
				}
				} finally { DebugExitDecision(11); }
				switch (alt11)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:48:28: '\\r'
					{
					DebugLocation(48, 28);
					Match('\r'); 

					}
					break;

				}
				} finally { DebugExitSubRule(11); }

				DebugLocation(48, 34);
				Match('\n'); 
				DebugLocation(48, 39);
				_channel=Hidden;

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:49:9: '/*' ( options {greedy=false; } : . )* '*/'
				{
				DebugLocation(49, 9);
				Match("/*"); 

				DebugLocation(49, 14);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:49:14: ( options {greedy=false; } : . )*
				try { DebugEnterSubRule(12);
				while (true)
				{
					int alt12=2;
					try { DebugEnterDecision(12, false);
					int LA12_0 = input.LA(1);

					if ((LA12_0=='*'))
					{
						int LA12_1 = input.LA(2);

						if ((LA12_1=='/'))
						{
							alt12 = 2;
						}
						else if (((LA12_1>='\u0000' && LA12_1<='.')||(LA12_1>='0' && LA12_1<='\uFFFF')))
						{
							alt12 = 1;
						}


					}
					else if (((LA12_0>='\u0000' && LA12_0<=')')||(LA12_0>='+' && LA12_0<='\uFFFF')))
					{
						alt12 = 1;
					}


					} finally { DebugExitDecision(12); }
					switch ( alt12 )
					{
					case 1:
						DebugEnterAlt(1);
						// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:49:42: .
						{
						DebugLocation(49, 42);
						MatchAny(); 

						}
						break;

					default:
						goto loop12;
					}
				}

				loop12:
					;

				} finally { DebugExitSubRule(12); }

				DebugLocation(49, 47);
				Match("*/"); 

				DebugLocation(49, 52);
				_channel=Hidden;

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 5);
			LeaveRule("COMMENT", 5);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 6);
		TraceIn("WS", 6);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:52:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:52:9: ( ' ' | '\\t' | '\\r' | '\\n' )
			{
			DebugLocation(52, 9);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(56, 11);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 6);
			LeaveRule("WS", 6);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_STRING();
	partial void LeaveRule_STRING();

	// $ANTLR start "STRING"
	[GrammarRule("STRING")]
	private void mSTRING()
	{
		EnterRule_STRING();
		EnterRule("STRING", 7);
		TraceIn("STRING", 7);
		try
		{
			int _type = STRING;
			int _channel = DefaultTokenChannel;
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:60:5: ( '\"' ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )* '\"' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:60:8: '\"' ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )* '\"'
			{
			DebugLocation(60, 8);
			Match('\"'); 
			DebugLocation(60, 12);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:60:12: ( ESC_QUOTE |~ ( '\\\\' | '\"' ) )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=3;
				try { DebugEnterDecision(14, false);
				int LA14_0 = input.LA(1);

				if ((LA14_0=='\"'))
				{
					int LA14_1 = input.LA(2);

					if ((LA14_1=='\"'))
					{
						alt14 = 1;
					}


				}
				else if (((LA14_0>='\u0000' && LA14_0<='!')||(LA14_0>='#' && LA14_0<='[')||(LA14_0>=']' && LA14_0<='\uFFFF')))
				{
					alt14 = 2;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:60:14: ESC_QUOTE
					{
					DebugLocation(60, 14);
					mESC_QUOTE(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:60:26: ~ ( '\\\\' | '\"' )
					{
					DebugLocation(60, 26);
					input.Consume();


					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(60, 41);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING", 7);
			LeaveRule("STRING", 7);
			LeaveRule_STRING();
		}
	}
	// $ANTLR end "STRING"

	partial void EnterRule_EXPONENT();
	partial void LeaveRule_EXPONENT();

	// $ANTLR start "EXPONENT"
	[GrammarRule("EXPONENT")]
	private void mEXPONENT()
	{
		EnterRule_EXPONENT();
		EnterRule("EXPONENT", 8);
		TraceIn("EXPONENT", 8);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:64:10: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:64:12: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
			{
			DebugLocation(64, 12);
			if (input.LA(1)=='E'||input.LA(1)=='e')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(64, 22);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:64:22: ( '+' | '-' )?
			int alt15=2;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_0 = input.LA(1);

			if ((LA15_0=='+'||LA15_0=='-'))
			{
				alt15 = 1;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
				{
				DebugLocation(64, 22);
				input.Consume();


				}
				break;

			}
			} finally { DebugExitSubRule(15); }

			DebugLocation(64, 33);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:64:33: ( '0' .. '9' )+
			int cnt16=0;
			try { DebugEnterSubRule(16);
			while (true)
			{
				int alt16=2;
				try { DebugEnterDecision(16, false);
				int LA16_0 = input.LA(1);

				if (((LA16_0>='0' && LA16_0<='9')))
				{
					alt16 = 1;
				}


				} finally { DebugExitDecision(16); }
				switch (alt16)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
					{
					DebugLocation(64, 33);
					input.Consume();


					}
					break;

				default:
					if (cnt16 >= 1)
						goto loop16;

					EarlyExitException eee16 = new EarlyExitException( 16, input );
					DebugRecognitionException(eee16);
					throw eee16;
				}
				cnt16++;
			}
			loop16:
				;

			} finally { DebugExitSubRule(16); }


			}

		}
		finally
		{
			TraceOut("EXPONENT", 8);
			LeaveRule("EXPONENT", 8);
			LeaveRule_EXPONENT();
		}
	}
	// $ANTLR end "EXPONENT"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 9);
		TraceIn("HEX_DIGIT", 9);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:67:11: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' ) )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:
			{
			DebugLocation(67, 11);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='A' && input.LA(1)<='F')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 9);
			LeaveRule("HEX_DIGIT", 9);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_ESC_QUOTE();
	partial void LeaveRule_ESC_QUOTE();

	// $ANTLR start "ESC_QUOTE"
	[GrammarRule("ESC_QUOTE")]
	private void mESC_QUOTE()
	{
		EnterRule_ESC_QUOTE();
		EnterRule("ESC_QUOTE", 10);
		TraceIn("ESC_QUOTE", 10);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:71:5: ( '\"' '\"' )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:71:9: '\"' '\"'
			{
			DebugLocation(71, 9);
			Match('\"'); 
			DebugLocation(71, 13);
			Match('\"'); 

			}

		}
		finally
		{
			TraceOut("ESC_QUOTE", 10);
			LeaveRule("ESC_QUOTE", 10);
			LeaveRule_ESC_QUOTE();
		}
	}
	// $ANTLR end "ESC_QUOTE"

	partial void EnterRule_OCTAL_ESC();
	partial void LeaveRule_OCTAL_ESC();

	// $ANTLR start "OCTAL_ESC"
	[GrammarRule("OCTAL_ESC")]
	private void mOCTAL_ESC()
	{
		EnterRule_OCTAL_ESC();
		EnterRule("OCTAL_ESC", 11);
		TraceIn("OCTAL_ESC", 11);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:76:5: ( '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) ( '0' .. '7' ) | '\\\\' ( '0' .. '7' ) )
			int alt17=3;
			try { DebugEnterDecision(17, false);
			int LA17_0 = input.LA(1);

			if ((LA17_0=='\\'))
			{
				int LA17_1 = input.LA(2);

				if (((LA17_1>='0' && LA17_1<='3')))
				{
					int LA17_2 = input.LA(3);

					if (((LA17_2>='0' && LA17_2<='7')))
					{
						int LA17_4 = input.LA(4);

						if (((LA17_4>='0' && LA17_4<='7')))
						{
							alt17 = 1;
						}
						else
						{
							alt17 = 2;
						}
					}
					else
					{
						alt17 = 3;
					}
				}
				else if (((LA17_1>='4' && LA17_1<='7')))
				{
					int LA17_3 = input.LA(3);

					if (((LA17_3>='0' && LA17_3<='7')))
					{
						alt17 = 2;
					}
					else
					{
						alt17 = 3;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 17, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 17, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(17); }
			switch (alt17)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:76:9: '\\\\' ( '0' .. '3' ) ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(76, 9);
				Match('\\'); 
				DebugLocation(76, 14);
				input.Consume();

				DebugLocation(76, 25);
				input.Consume();

				DebugLocation(76, 36);
				input.Consume();


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:77:9: '\\\\' ( '0' .. '7' ) ( '0' .. '7' )
				{
				DebugLocation(77, 9);
				Match('\\'); 
				DebugLocation(77, 14);
				input.Consume();

				DebugLocation(77, 25);
				input.Consume();


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:78:9: '\\\\' ( '0' .. '7' )
				{
				DebugLocation(78, 9);
				Match('\\'); 
				DebugLocation(78, 14);
				input.Consume();


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCTAL_ESC", 11);
			LeaveRule("OCTAL_ESC", 11);
			LeaveRule_OCTAL_ESC();
		}
	}
	// $ANTLR end "OCTAL_ESC"

	partial void EnterRule_UNICODE_ESC();
	partial void LeaveRule_UNICODE_ESC();

	// $ANTLR start "UNICODE_ESC"
	[GrammarRule("UNICODE_ESC")]
	private void mUNICODE_ESC()
	{
		EnterRule_UNICODE_ESC();
		EnterRule("UNICODE_ESC", 12);
		TraceIn("UNICODE_ESC", 12);
		try
		{
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:83:5: ( '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT )
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:83:9: '\\\\' 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
			{
			DebugLocation(83, 9);
			Match('\\'); 
			DebugLocation(83, 14);
			Match('u'); 
			DebugLocation(83, 18);
			mHEX_DIGIT(); 
			DebugLocation(83, 28);
			mHEX_DIGIT(); 
			DebugLocation(83, 38);
			mHEX_DIGIT(); 
			DebugLocation(83, 48);
			mHEX_DIGIT(); 

			}

		}
		finally
		{
			TraceOut("UNICODE_ESC", 12);
			LeaveRule("UNICODE_ESC", 12);
			LeaveRule_UNICODE_ESC();
		}
	}
	// $ANTLR end "UNICODE_ESC"

	public override void mTokens()
	{
		// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:8: ( TYPE | ID | INT | FLOAT | COMMENT | WS | STRING )
		int alt18=7;
		try { DebugEnterDecision(18, false);
		try
		{
			alt18 = dfa18.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(18); }
		switch (alt18)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:10: TYPE
			{
			DebugLocation(1, 10);
			mTYPE(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:15: ID
			{
			DebugLocation(1, 15);
			mID(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:18: INT
			{
			DebugLocation(1, 18);
			mINT(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:22: FLOAT
			{
			DebugLocation(1, 22);
			mFLOAT(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:28: COMMENT
			{
			DebugLocation(1, 28);
			mCOMMENT(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:36: WS
			{
			DebugLocation(1, 36);
			mWS(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\Users\\aaron\\projects\\ttcn3\\csharp\\TTCN3.g:1:39: STRING
			{
			DebugLocation(1, 39);
			mSTRING(); 

			}
			break;

		}

	}


	#region DFA
	DFA9 dfa9;
	DFA18 dfa18;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa9 = new DFA9(this);
		dfa18 = new DFA18(this);
	}

	private class DFA9 : DFA
	{
		private const string DFA9_eotS =
			"\x5\xFFFF";
		private const string DFA9_eofS =
			"\x5\xFFFF";
		private const string DFA9_minS =
			"\x2\x2E\x3\xFFFF";
		private const string DFA9_maxS =
			"\x1\x39\x1\x65\x3\xFFFF";
		private const string DFA9_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1\x1\x3";
		private const string DFA9_specialS =
			"\x5\xFFFF}>";
		private static readonly string[] DFA9_transitionS =
			{
				"\x1\x2\x1\xFFFF\xA\x1",
				"\x1\x3\x1\xFFFF\xA\x1\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"",
				""
			};

		private static readonly short[] DFA9_eot = DFA.UnpackEncodedString(DFA9_eotS);
		private static readonly short[] DFA9_eof = DFA.UnpackEncodedString(DFA9_eofS);
		private static readonly char[] DFA9_min = DFA.UnpackEncodedStringToUnsignedChars(DFA9_minS);
		private static readonly char[] DFA9_max = DFA.UnpackEncodedStringToUnsignedChars(DFA9_maxS);
		private static readonly short[] DFA9_accept = DFA.UnpackEncodedString(DFA9_acceptS);
		private static readonly short[] DFA9_special = DFA.UnpackEncodedString(DFA9_specialS);
		private static readonly short[][] DFA9_transition;

		static DFA9()
		{
			int numStates = DFA9_transitionS.Length;
			DFA9_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA9_transition[i] = DFA.UnpackEncodedString(DFA9_transitionS[i]);
			}
		}

		public DFA9( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 9;
			this.eot = DFA9_eot;
			this.eof = DFA9_eof;
			this.min = DFA9_min;
			this.max = DFA9_max;
			this.accept = DFA9_accept;
			this.special = DFA9_special;
			this.transition = DFA9_transition;
		}

		public override string Description { get { return "41:1: FLOAT : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ EXPONENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA18 : DFA
	{
		private const string DFA18_eotS =
			"\x1\xFFFF\x1\x2\x1\xFFFF\x1\x9\x4\xFFFF\x1\x2\x1\xFFFF\x1\x2\x1\xC\x1"+
			"\xFFFF";
		private const string DFA18_eofS =
			"\xD\xFFFF";
		private const string DFA18_minS =
			"\x1\x9\x1\x79\x1\xFFFF\x1\x2E\x4\xFFFF\x1\x70\x1\xFFFF\x1\x65\x1\x30"+
			"\x1\xFFFF";
		private const string DFA18_maxS =
			"\x1\x7A\x1\x79\x1\xFFFF\x1\x65\x4\xFFFF\x1\x70\x1\xFFFF\x1\x65\x1\x7A"+
			"\x1\xFFFF";
		private const string DFA18_acceptS =
			"\x2\xFFFF\x1\x2\x1\xFFFF\x1\x4\x1\x5\x1\x6\x1\x7\x1\xFFFF\x1\x3\x2\xFFFF"+
			"\x1\x1";
		private const string DFA18_specialS =
			"\xD\xFFFF}>";
		private static readonly string[] DFA18_transitionS =
			{
				"\x2\x6\x2\xFFFF\x1\x6\x12\xFFFF\x1\x6\x1\xFFFF\x1\x7\xB\xFFFF\x1\x4"+
				"\x1\x5\xA\x3\x7\xFFFF\x1A\x2\x4\xFFFF\x1\x2\x1\xFFFF\x13\x2\x1\x1\x6"+
				"\x2",
				"\x1\x8",
				"",
				"\x1\x4\x1\xFFFF\xA\x3\xB\xFFFF\x1\x4\x1F\xFFFF\x1\x4",
				"",
				"",
				"",
				"",
				"\x1\xA",
				"",
				"\x1\xB",
				"\xA\x2\x7\xFFFF\x1A\x2\x4\xFFFF\x1\x2\x1\xFFFF\x1A\x2",
				""
			};

		private static readonly short[] DFA18_eot = DFA.UnpackEncodedString(DFA18_eotS);
		private static readonly short[] DFA18_eof = DFA.UnpackEncodedString(DFA18_eofS);
		private static readonly char[] DFA18_min = DFA.UnpackEncodedStringToUnsignedChars(DFA18_minS);
		private static readonly char[] DFA18_max = DFA.UnpackEncodedStringToUnsignedChars(DFA18_maxS);
		private static readonly short[] DFA18_accept = DFA.UnpackEncodedString(DFA18_acceptS);
		private static readonly short[] DFA18_special = DFA.UnpackEncodedString(DFA18_specialS);
		private static readonly short[][] DFA18_transition;

		static DFA18()
		{
			int numStates = DFA18_transitionS.Length;
			DFA18_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA18_transition[i] = DFA.UnpackEncodedString(DFA18_transitionS[i]);
			}
		}

		public DFA18( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 18;
			this.eot = DFA18_eot;
			this.eof = DFA18_eof;
			this.min = DFA18_min;
			this.max = DFA18_max;
			this.accept = DFA18_accept;
			this.special = DFA18_special;
			this.transition = DFA18_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( TYPE | ID | INT | FLOAT | COMMENT | WS | STRING );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

 
	#endregion

}
